language: python
cache: pip
dist: xenial

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -U pip setuptools setuptools_scm
  - pip install -r requirements.txt
  - pip install pytest scipy hdf5 torch pydrobert-kaldi

script:
  - python setup.py test
