version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39  # not there yet

stack: python 3.7

build: off

init:
  - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install:
  - python -m pip install tox tox-appveyor

test_script:
  - python -m tox