version: build.{build}.branch.{branch}

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    # - TOXENV: py39  # not there yet

build: off

install:
  - pip install tox

test_script:
  - tox