version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39

build: off

install:
  - py -3.7 -m pip install -U pip tox wheel tox-appveyor

test_script:
  - py -3.7 -m tox