version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39  # not there yet

build: off

install:
  - python3 -m pip install tox

test_script:
  - python3 -m tox